# Generated by Django 5.1.3 on 2024-12-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRiver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradasCopa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=25)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EntradasTorneoLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=25)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Entradas',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='fecha_inicio',
        ),
    ]
